AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/exiftool_test.rb'
    - 'exiftool_vendored.gemspec'

Style/SpecialGlobalVars:
  Exclude:
    - exiftool_vendored.gemspec