require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/exiftool_test.rb'
    - 'exiftool_vendored.gemspec'

Style/SpecialGlobalVars:
  Exclude:
    - exiftool_vendored.gemspec
