AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/exiftool_test.rb'

Style/SpecialGlobalVars:
  Exclude:
    - exiftool_vendored.gemspec