AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/exiftool_test.rb'

Style/SpecialGlobalVars:
  Exclude:
    - exiftool_vendored.gemspec